# Generated by Django 5.1.7 on 2025-04-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cart_fooditem_order_delete_student_cart_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('rating', models.FloatField(default=0.0)),
                ('views', models.PositiveIntegerField(default=0)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Food Category',
                'verbose_name_plural': 'Food Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('South Indian', 'South Indian'), ('Special Thali', 'Special Thali'), ('Momos', 'Momos'), ('Cake', 'Cake'), ('Pizza', 'Pizza'), ('Soup', 'Soup'), ('Salad', 'Salad'), ('Juice & Mocktails', 'Juice & Mocktails'), ('Non Veg', 'Non Veg'), ('Chinese', 'Chinese'), ('Italian', 'Italian'), ('Dessert', 'Dessert'), ('Veg', 'Veg'), ('Chaat', 'Chaat')], max_length=50)),
                ('price', models.IntegerField()),
                ('pre_piece', models.IntegerField()),
                ('likes', models.IntegerField()),
                ('prep_time', models.CharField(max_length=50)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views', models.IntegerField()),
                ('rating', models.FloatField()),
                ('preTime', models.CharField(max_length=50)),
                ('deliveryFee', models.IntegerField()),
                ('description', models.TextField()),
                ('ingredients', models.JSONField(default=list)),
                ('nutrients', models.JSONField(default=dict)),
                ('quantity', models.IntegerField(default=0)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
            },
        ),
        migrations.DeleteModel(
            name='FoodItem',
        ),
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(to='api.menuitem'),
        ),
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='api.menuitem'),
        ),
    ]
