# Generated by Django 5.1.7 on 2025-04-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_category_menulistitem_remove_cart_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='prepTime',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='servingSize',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
