# Generated by Django 5.1.7 on 2025-04-03 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_category_preptime_category_servingsize'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menulistitem',
            name='delivery_fee',
        ),
    ]
