# Generated by Django 5.1.7 on 2025-04-03 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_menulistitem_delivery_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menulistitem',
            old_name='pre_time',
            new_name='preTime',
        ),
    ]
