# Generated by Django 5.1.7 on 2025-04-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_orders_dish_name_remove_orders_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='image',
            field=models.URLField(default=40),
            preserve_default=False,
        ),
    ]
