# Generated by Django 5.1.7 on 2025-04-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_orders_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='dish',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='orders',
            name='quantity',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='orders',
            name='user_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
