# Generated by Django 5.1.7 on 2025-04-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menulistitem',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='menulistitem',
            name='image',
            field=models.URLField(max_length=500),
        ),
    ]
