# Generated by Django 5.1.7 on 2025-04-03 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_data', '0002_alter_menulistitem_category_alter_menulistitem_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menulistitem',
            old_name='delivery_fee',
            new_name='deliveryFee',
        ),
        migrations.RenameField(
            model_name='menulistitem',
            old_name='pre_time',
            new_name='preTime',
        ),
    ]
